### ISSUE TITLE
Visually distinguish directories from files

### ISSUE THREAD

**Issue by erusev** [jhawthorn/fzy#102]
What would be the easiest way to visually distinguish directories from files in `fzy` output? For example, make folders bold and blue while files remain white.

**Comment by jhawthorn** [comment]
Thanks for the suggestion but since fzy accepts arbitrary input (it isn't necessarily files) I don't think there's a good way to do this. One thing you could do have whatever program provides input add a trailing `/` to directories.

**Comment by erusev** [comment]
Thanks! Makes sense.
