### ISSUE TITLE
Using TAB to go down instead of autocomplete 

### ISSUE THREAD

**Issue by 4vrel** [jhawthorn/fzy#104]
Hello !
I would like to make TAB going down instead of autocomplete.
I tried to hack tty_interface.c but didnt succed to find where and how the TAB keybinding was handled.
It looks like its handled by CTRL+I witch is a bit weird.
peace

**Comment by neuschaefer** [comment]
A tabulator is encoded in ASCII as the number 9, which also corresponds to Ctrl-I. In other words, you've found it.

**Comment by 4vrel** [comment]
I see .. so Ctrl-I and TAB can't be dissociated .
Should I make a pull request ? 
I feel like going down is more usefull than autocomplete ( is autocomplete usefull at all ? ) therefore it should be on a easier keybinding ( down-arrow and ctrl-n are way too work compared to TAB )

**Comment by neuschaefer** [comment]
IMHO, Ctrl-j/k for down/up is convenient enough, but I don't make decisions here.

**Comment by casr** [comment]
I guess you could have first tab completes the match, n+1 tab then cycles over the matches.

**Comment by jhawthorn** [comment]
I don't think there's enough interest in this. Thanks for the suggestion.

I find tab occasionally useful for the ability to add additional text in the returned result (ex. to make a new similarly named file).
