### ISSUE TITLE
Zplug instruction

### ISSUE THREAD

**Issue by soullivaneuh** [jhawthorn/fzy#106]
Hi,

May we have a zplug instruction on the README?

I tried this:

```
zplug "jhawthorn/fzy", from:gh-r, as:command, rename-to:fzy, \
  use:"fzy-*.tar.gz", \
  hook-build:"make"
```

Without success. :-/

**Comment by neuschaefer** [comment]
How did it fail?

**Comment by jhawthorn** [comment]
Sorry, I don't know zplug. If anyone finds a solution please add it to the wiki ❤️
