### ISSUE TITLE
GVim integration

### ISSUE THREAD

**Issue by julien** [jhawthorn/fzy#110]
Hi, 

Fist thanks for this project, it's pretty useful.

The README.md has a good example of how to use this with vim, but I was wondering if it's possible to do the same in GVim

Thanks

**Comment by neuschaefer** [comment]
I have not tried this, but since gvim doesn't run in a terminal, you may have to start a terminal in the piece of vimscript that starts fzy. It definitely seems possible to me.

**Comment by julien** [comment]
Thanks @neuschaefer 
No idea how I'd do that but I'll search and fiddle around with vimscript.

**Comment by casr** [comment]
I think vim-picker works in gvim 8.1+ but I haven't tried it. https://github.com/srstevenson/vim-picker
