### ISSUE TITLE
Bash: Insert fuzzy-found paths directly into the shell command line

### ISSUE THREAD

**Issue by jetm** [jhawthorn/fzy#126]
Using bash, I want to insert fuzzy-found paths directly into the shell command line. Have try several options following Zsh Wiki example, but I have been unable to get it working.

**Comment by Konfekt** [comment]
Have a look at the `fuzzyfinders.bash` at https://github.com/Konfekt/fuzzyfinders.sh for an example. Feel free to ask for further advice or clarifications.

**Comment by jetm** [comment]
@Konfekt Thanks. I will look on that.
