### ISSUE TITLE
Ranger integration example

### ISSUE THREAD

**Issue by henryoliver** [jhawthorn/fzy#128]
Hi there, great work on this fuzzy text selector! It's really fast!

I would like to use fzy instead of fzf on my ranger workflow. Please, can you provide an example of it similar to the link below?
https://github.com/ranger/ranger/wiki/Custom-Commands#fzf-integration

Thanks!

**Comment by casr** [comment]
What happens if you try to replace `fzf +m` with `fzy` in that snippet?

**Comment by henryoliver** [comment]
Worked like a charm! Thanks @casr!
