### ISSUE TITLE
Right align output by default

### ISSUE THREAD

**Issue by GSI** [jhawthorn/fzy#13]
Currently long lines are simply cut off **on** the right, making it impossible to differenciate between lines that have the same beginning, like particulary long paths:

    /home/jh/imagine/a/long/path/here/somefile.txt
    /home/jh/imagine/a/long/path/here/otherfile.txt

... will display as:

    /home/jh/imagine/a/long/pa
    /home/jh/imagine/a/long/pa

... should rather display as:

    th/here/somefile.txt
    th/here/otherfile.txt

*(BTW the speed advantage of fzy over fzf is impressive)*

**Comment by jhawthorn** [comment]
I don't think right-aligning is the right thing to do. I don't know of any other unix tool which do this and I think the behaviour would be confusing.

I would, however, like to think of a way to see the rightmost portions of a match if they don't fit on the screen (like `less` allows with the right and left arrows, for example)
