### ISSUE TITLE
Feature requests for handhelds

### ISSUE THREAD

**Issue by jarun** [jhawthorn/fzy#135]
I use `fzy` regularly on my handheld device with file manager [`nnn`](https://github.com/jarun/nnn) (I am the author of the tool). I'm really happy with the performance on a mid-range Android device.

From months of usage, I believe the following enhancements would improve the user experience on smaller form-factors greatly:

- Most of the time I search files like documents of music. If I haven't missed it, currently there is no way to match only the filename instead of the full path. If such an option is vailable, that would reduce the number results and show more accurate ones in this use case.
- On smaller screens, path folding would help a lot. Most of the time I can't see the file name, only the path and if there are more than one matches in the path, it's kind of a blind guess. In case it helps, here's an example path folding logic in `nnn`: https://github.com/jarun/nnn/blob/v2.8.1/src/nnn.c#L4045-L4066

Once again, thanks for the great little utility!

**Comment by zvezdochiot** [comment]
@jarun say:
>On smaller screens, path folding would help a lot. Most of the time I can't see the file name, only the path and if there are more than one matches in the path, it's kind of a blind guess. In case it helps, here's an example path folding logic in nnn: https://github.com/jarun/nnn/blob/v2.8.1/src/nnn.c#L4045-L4066

Or https://github.com/motersen/pwdxz

**Comment by jarun** [comment]
@zvezdochiot very useful for us devs and I am having it in right away. The problem is, compilation turns off end users. That's why I am looking for something that's built in `fzy`.

Also, we still need the first one, to search only files (excluding paths). So both the requests kind go hand in hand.

**Comment by jarun** [comment]
@jhawthorn any plans to have these in?

**Comment by jarun** [comment]
Ignore this. `nnn` has dropped `fzy` support so this feature request isn't relevant to the project anymore.
