### ISSUE TITLE
fzy-tmux: line 41: exit: : numeric argument required

### ISSUE THREAD

**Issue by d-e-s-o** [jhawthorn/fzy#143]
I am seeing occasional issues with the `fzy-tmux` script. I use it to navigate between different directories inside `vifm` and sometimes this step fails. I believe all the issues I have seen ultimately came down to the return code handling, but most of the time pretty much all context is lost.

I use the following command invocation:
```sh
$ fd --type d | fzy-tmux
```
And managed to reproduce the issue from a shell and saw:
```
head: cannot open '/tmp/tmp.qUbDwrPLxQ/ret' for reading: No such file or directory
/usr/bin/fzy-tmux: line 41: exit: : numeric argument required
```
That maps to [this line](https://github.com/jhawthorn/fzy/blob/c2d816d9e31cf9e2ebaf2b51b346ab2a992d7457/contrib/fzy-tmux#L41). Seems we are racing with the removal of the file (or perhaps the creation?), but it's not obvious to me why.

Any ideas?

**Comment by zsugabubus** [comment]
Maybe it can occur if:
1. fzy finished, `> '${PATH_FIFO_OUT}'` closed.
2. `cat < "${PATH_FIFO_OUT}"` finishes because got EOF.
3. `head -n 1 "${PATH_FIFO_RET}"` does not find file because `echo $? > '${PATH_FIFO_RET}'` did not created it yet.

Guess it could help if RET would be also a(n existing) pipe, so `head` waits until `echo $?` writes it. Try this:
```
mkfifo "${PATH_FIFO_IN}" "${PATH_FIFO_OUT}" "${PATH_FIFO_RET}"
```

**Comment by d-e-s-o** [comment]
Thanks for your quick response. Very well possible. Interestingly I am not able to reproduce the issue even without your patch now. There must be some environmental/configuration component to it, because I had virtually the same setup for ages now and sometimes I see it clustered. I'll wait until I have a reproduction and then try out your patch.

**Comment by zsugabubus** [comment]
I think you never will have a sure way to reproduce this because it depends on OS scheduling that you can hardly predict.

**Comment by d-e-s-o** [comment]
> (But you can simulate a bigger delay by inserting a `sleep 1` before `echo $?`.)

Good idea. Works. Thanks! Will you push that change upstream or do you want me to create a pull request?

**Comment by zsugabubus** [comment]
You have a tested, working solution, so yes, maybe it would be better if you would make a PR.
