### ISSUE TITLE
Maintainers wanted?

### ISSUE THREAD

**Issue by HaleTom** [jhawthorn/fzy#168]
Thanks so much @jhawthorn for creating this project!

Because of the number of open pull requests and the last code update of 12 Oct 2020,  I'm wondering how it fits into your life to ongoingly maintain it?

If you've moved on to other life priorities, perhaps accepting the trivial documentation PRs (to update the last change date) and moving this into a community repo would spur some more interest and support?

I could assist with documentation and more obvious PRs, but don't have life-space for diving into the algorithm guts right now.

**Comment by jhawthorn** [comment]
No thanks
