### ISSUE TITLE
Present interim results immediately when reading from pipe (like fzf)

### ISSUE THREAD

**Issue by HaleTom** [jhawthorn/fzy#169]
The behaviour of the two commands:
```
find / | fzf
````

```
find / | fzy
````

Is quite different.  With `fzf`, results start appearing immediately.  Could `fzy` also behave the same?

**Comment by jhawthorn** [comment]
This has already been discussed in detail. I believe results appearing before they are ready to be a UI anti pattern. Even though it "feels" better, it results in mistakes, as incorrect data is presented to the user (sort order matters in a fuzzy finder)
