### ISSUE TITLE
Support streaming

### ISSUE THREAD

**Issue by simnalamburt** [jhawthorn/fzy#17]
Current fzy implementation waits until `stdin` ends. Which is undesirable if input program takes a very long time or does not have the end. For example,
- `find . | fzy` in **Windows**
- `cat ./unix_socket | fzy`

I'm fzf user but I'm using fzy in Windows. If fzy supports streaming I can finally move away from fzf. Do you have any plan to support streaming?

**Comment by pbogut** [comment]
That's a deal breaker for me, as In my projects I have to wait around 2 secs to result to pop up while fzf shows up immediately.

**Comment by balta2ar** [comment]
@simnalamburt @pbogut You may want to look 0.15.0 release of fzf where ranking algorithm has been revised: https://github.com/junegunn/fzf/commit/2fc7c18747250ebf8adf68d2057ec22af6976f29. Maybe it fits you better now.

**Comment by simnalamburt** [comment]
@balta2ar I'm using fzy because of its nice windows support. As far as I know, fzf do not have any special plan for windows yet.

**Comment by jhawthorn** [comment]
I've investigated `fzf`, and I don't like how it treats streaming input.

If you type your search really fast and hit enter, it will return whatever "temporary" result it has found from the input it had up to that point. I don't want this behaviour in `fzy` I find it really important for software to behave deterministically, and for UI interactions to be consistent, so I don't want to return results before the input has been read.

I also don't see a middle group of streaming which would work acceptably well. Displaying results but not allowing selection wouldn't save time, and could be confusing to users, who might think they were about to select one result only to have it replaced by a better one (which took a while to arrive in the input).

If you're finding that the input comes in too slow, please try using `ag` to generate the input to fzy. It lists files seriously fast, and `fzy` can read its input very fast as well.

**Comment by Exr0n** [comment]
@jhawthorn I understand your desire for software to be have deterministically, but I'm hoping you can elaborate on what you mean by consistent UI interactions?

I also understand that typing a search quickly and hitting enter indeed returns a non-deterministic result, but I personally use `fzy` to search for something I have in mind and I would visually confirm that it has selected what I want before hitting enter. I can't imagine typing and confirming that quickly is a very common use case...

Thank you for taking this into consideration again.
