### ISSUE TITLE
Segfault when using fzy if the filename contains non-ASCII character(s)

### ISSUE THREAD

**Issue by aksr** [jhawthorn/fzy#18]
If the directory contains, for example, the following name:

    Edmund Husserl - Méditations cartésiennes - Introduction a la phénoménologie.pdf

and if I execute, for example:

    ls -l | fzy
The program segfaults. (This `é` is the problem.)
Easily reproducible: *just create a filename with the above name and run the above command*.

**Comment by jhawthorn** [comment]
Thanks for the report. This should be fixed by 7812c553d33ce105afbc7696fb9e01ca92fba2ea which I've released as version 0.7
