### ISSUE TITLE
A "Use of Uninitialized Variable" bug occurs in file match.c

### ISSUE THREAD

**Issue by Nick-Morbid** [jhawthorn/fzy#188]
I hope this message finds you well. I have identified a potential "Use of Uninitialized Variable" bug in the project, and I would like to bring it to your attention in case it may be helpful. This bug might lead to unexpected behavior due to the usage of uninitialized variables, potentially affecting program stability. Can you please help me check it? Thank you for your effort and patience!

Bug Description:
The bug is located in the file src/match.c, involving the functions `match_positions` and `match_row`. The specific code flow is as follows:
1. In the `match_positions` function, on line 188, two pointers, `last_D` and `last_M`, are declared but not initialized.
2. The code on line 195, within `match_positions`, directly uses these uninitialized pointers as parameters and passes them into the `match_row` function.
3. Within the `match_row` function, on lines 90 and 92, data is accessed through `last_D` and `last_M`, leading to a "Use of Uninitialized Variable" bug.
![bug report](https://github.com/user-attachments/assets/11266943-7631-4bbc-b339-f896f7877a17)

**Comment by jhawthorn** [comment]
Thanks! Fixed in b2389a67fcd4102370ec600418be0743944be3b2

I don't think this could ever be dereferenced in its uninitialized form, since it's only uninitialized for i=0, but this is good to fix.
