### ISSUE TITLE
Proper handling of UTF-8

### ISSUE THREAD

**Issue by aksr** [jhawthorn/fzy#21]
Thanks for fixing the previous (utf-8) bug.
If the filename contains some non-ASCII character, fzy doesn't segfault anymore.
Having that in mind,  it's not possible to insert (while seaching) some non-ASCII character.
If I insert characters like `öäßéè` etc., fzy doesn't show anything.

Best regards.

**Comment by slashbeast** [comment]
Ping @jhawthorn 
Any comment on the UTF-8 or non-ASCII insert mode?
