### ISSUE TITLE
Multi-select

### ISSUE THREAD

**Issue by aktau** [jhawthorn/fzy#22]
Hi! I'd like to try out `fzy` as a replacement with `fzf` for my workflows because of the better ranking. (Thanks for the great software and simple Makefile). However, I have one use case that's important to me but `fzy` doesn't provide AFAIK: opening multiple files I've selected in Vim (in splits or buffers):

Simplified:

```
# Open files listed on stdin in $EDITOR.
vimin () {
	runargs ${EDITOR:-vim} -O
}

# Can select multiple files and have them open in splits.
ag | fzf -0 -1 -m | vimin

# No multi-select.
ag | fzy | vimin
```

(The lack of streaming matching is also a bit problematic, which is why I +1'd the issue discussing this. I often use a FUSE network filesystem which cannot reasonably be queried, but I like to get the first levels of matches with something like https://github.com/tavianator/bfs.)

**Comment by balta2ar** [comment]
@aktau You may want to look 0.15.0 release of fzf where ranking algorithm has been revised: https://github.com/junegunn/fzf/commit/2fc7c18747250ebf8adf68d2057ec22af6976f29. Maybe it fits you better now.

**Comment by aktau** [comment]
Thanks! That'll do for now I think :).
