### ISSUE TITLE
Direct setting of empty strings

### ISSUE THREAD

**Issue by elfring** [jhawthorn/fzy#29]
[Empty strings](https://en.wikipedia.org/wiki/Empty_string#Use_in_programming_languages "Description for the usage of empty strings") are copied by a function call at [some source code places](https://github.com/jhawthorn/fzy/blob/5a3ce8bad8af2f65755bcde223129e240c53b46c/src/tty_interface.c#L196 "Update candidate: tty_interface_init()").
How do you think about to set the corresponding string terminator for the involved buffers directly?

Example:
```diff
-	strcpy(state->search, "");
+	*state->search = '\0';
```

**Comment by jhawthorn** [comment]
I don't think there's a compelling reason to change this.
