### ISSUE TITLE
Wrong result dealing with control escape chars

### ISSUE THREAD

**Issue by delta4d** [jhawthorn/fzy#33]
![escape](https://cloud.githubusercontent.com/assets/2194462/23988348/cbef601a-0a68-11e7-9735-aeb73686ad4e.png)

![escape_semi](https://cloud.githubusercontent.com/assets/2194462/23988477/636abbba-0a69-11e7-8984-82dc4ecea681.png)

![no_escape](https://cloud.githubusercontent.com/assets/2194462/23988287/81ece302-0a68-11e7-99b9-bc05a3793207.png)

Colored output contains escaped chars like `\x1b[30m;`, so pattern containing `m` or `;` may results wrong matches. 

I am aware there's always a workaround to remove the color. Or should `fzy` remove escape code while  `choices_fread`?

**Comment by jhawthorn** [comment]
`fzy` should not be aware of escape sequences, the matcher is doing the right thing here.  That's why instead of `ls --color=always` there is `ls --color=auto`.
