### ISSUE TITLE
Fzy doesn't redraw screen after executing command

### ISSUE THREAD

**Issue by Zaplanincan** [jhawthorn/fzy#4]
Hi, I'm using ArchLinux with st-256color terminal and tmux, with default install from AUR.
After executing `vim $(find -type f | fzy)` the last search line (10th) stay on screen after closing vim.
![](http://i1284.photobucket.com/albums/a568/Zaplanincan/Razno/screenshot-2016-04-27_zpsbqgg0mtf.jpg)

**Comment by jhawthorn** [comment]
Thanks so much for reporting @Zaplanincan (and luckily using my exact environment :+1:). I believe this is fixed in 60e3b9119c42c4a926d146f20bc64a193935b8f4.

If there's no issues I'll make a release shortly.
