### ISSUE TITLE
handle high load

### ISSUE THREAD

**Issue by jkoz** [jhawthorn/fzy#41]
Thank you for creating a fzf alternative in C. I love it!

I just did a compare bw fzf and fzy with command

find / | fzf
find / | fzy

fzy waits, but fzf runs right away with result avaiable from find. I wish we could add that feature to fzy.

I think this feature is critical when we working with big projects.

Thank you

**Comment by jhawthorn** [comment]
As I've explained in #17, there's real usability issues with running "right away" with available input. Basically, on fzf, if you type your input and enter too fast, it will return the wrong result. This is a flaw in the design of the streaming approach.

I think fzy does the right thing here, it doesn't display the interface until it can generate correct results (once it has read all the input). If you start typing before fzy starts it still does the right thing, using that as the query once the candidates are loaded.
