### ISSUE TITLE
Feature request: Allow movement to the beginning/end of the query

### ISSUE THREAD

**Issue by diamond-lizard** [jhawthorn/fzy#50]
It often happens that I start typing a query only to see that it's not matching what I want because I should have included some text at the beginning of the query.  My only option at that point is to abort the query and start over.

It would be nice if instead of aborting and starting over, fzy allowed me to enter text at the beginning of the query without deleting what I've already typed, and then also allow moving to the end of the typed query to continue typing there as well (if necessary).

(Ultimately, it would be ideal (for me) if fzy supported something like vim editing commands -- maybe through readline support.  But simply allowing one to add on to the beginning/end of the query would be a great enhancement.)

**Comment by jhawthorn** [comment]
This exists in the latest master! :tada:
