### ISSUE TITLE
Feature request: Regular expression search

### ISSUE THREAD

**Issue by diamond-lizard** [jhawthorn/fzy#52]
Today I needed to search for something that I knew occurred exactly at the end of a line.  I tried `$` but fzy took that to be the literal character `$`.  Then I tried `\$` and fzy interpreted those as two literal characters: `\` and `$`.

It would be great if fzy supported regular expression search.  Even supporting the most basic regex sequences like `^` and `$` would be really useful.

To maintain consistency with other regex engines, it would probably make sense to require the user to escape literals that clash with regexes, so that (for example) the user would have to type `\$` to get a literal `$` and `$` without a leading backslash would be interpreted as a regex.

**Comment by ohjames** [comment]
The way fzy's scoring system works isn't compatible with regexes.

**Comment by diamond-lizard** [comment]
Could a different scoring system be adopted just for the regexes?

**Comment by ohjames** [comment]
Simplest thing I can think of is to provide a secondary level of filtering via regex accessible via a key binding. This project isn't maintained anymore though.

**Comment by jhawthorn** [comment]
Unfortunately regexes aren't compatible with fzy's scoring system. There are interesting approaches which could be taken, like accepting regexes, but inserting `.*` between each character, but none of them really make sense, and defeat the original purpose of fzy.

There are likely other tools out there which support doing this. I want to keep fzy simple and unixy (doing only one thing well.). So I will not be adding this.

Thanks for the suggestion.
