### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by aksr** [jhawthorn/fzy#56]
1.` ls | fzy`
2. type anything (*more than a few words*)
3. C-a
4. C-w (*multiple times until everything is deleted; cursor goes suddenly right*)
5. Space (*maybe multiple times*)
6. **Segmentation fault**

**Comment by jhawthorn** [comment]
Thanks for the excellent report!

I believe this was caused by #46 which I've just partially rewritten and should be fixed by dc4e9b8abf678ce57172d1014a7fa0367926f386
