### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [jhawthorn/fzy#7]
Would you like to add more error handling for return values from functions like the following?
- [open](http://pubs.opengroup.org/onlinepubs/9699919799/functions/open.html) ⇒ [tty_init](https://github.com/jhawthorn/fzy/blob/24f8bcc162ad68cd24f49b9bf80f3396aa97255f/tty.c#L21)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) ⇒ [emit](https://github.com/jhawthorn/fzy/blob/d8d8248675b439a66bb30405f952509bf64070db/fzy.c#L93)

**Comment by jhawthorn** [comment]
I should definitely add error handling to these methods (especially `tty_init`, which could definitely fail). Thank you for catching.

**Comment by jhawthorn** [comment]
Errors in `tty_init` are now checked abe4d5c15876f7e0cb89524a3b2dc0d502f27b38

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Are there [a few update candidates left over](https://github.com/jhawthorn/fzy/blob/1f77253e52439a9441daa5748cb4e4f4a98bd18d/src/choices.c#L258 "Update candidate: choices_search()")?
