### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [jhawthorn/fzy#75]
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for fzy. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by jhawthorn** [comment]
Thanks for the suggestion. The 1.0 release includes this https://github.com/jhawthorn/fzy/releases/tag/1.0

**Comment by fcambus** [comment]
Thanks a lot! Just updated our package to 1.0.

**Comment by unode** [comment]
Would providing a static binary along with future releases be something you'd be willing to consider?
For convenience reasons mostly...
