### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [jhawthorn/fzy#8]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/jhawthorn/fzy/blob/b749877e5ea0d1112025c9c77852094d7c4b01dc/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](https://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by jhawthorn** [comment]
No thanks. I am very happy with my little makefile

**Comment by jhawthorn** [comment]
I should have asked, is there a system that fzy doesn't build on? If so I would want to either improve the makefile or (begrudgingly) add autotools.

I am a big fan of plain Makefiles. They're quite simple (like fzy is) and I think more powerful than commonly given credit for.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.5/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?
