### ISSUE TITLE
Cursor jumps to second line if enter is pressed before fzy starts

### ISSUE THREAD

**Issue by neuschaefer** [jhawthorn/fzy#81]
Hi,
I sometimes enter a search pattern (and press enter) faster than fzy starts up. I'd expect the first result to be selected in that case, but instead, the cursor moves to the second line.

Test case:
```
$ (echo a; echo b; echo c; sleep 1) | fzy<enter><enter>
```

I realize that this is because the code for CTRL-J is the same as '\n'. After fzy starts up, the enter key mapped to '\r', [via termios](https://github.com/jhawthorn/fzy/blob/master/src/tty.c#L47).

Thus, a solution would involve:
1. Reading the input once, non-blockingly; preferably before the terminal is configured with termios, to avoid false conversions from CTRL-J to '\r'
2. Replacing all occurences of '\n' with '\r' in the early input
3. Feeding the converted early input into the input state machine

I'm not sure the added complexity would be justified, so perhaps take this issue as the beginning of a discussion, rather than a bug report or feature request.

**Comment by jhawthorn** [comment]
Thanks for the report! I definitely want to fix this.

I have an alternate solution in #85, where I initialize the tty (which configures the termios) before reading in choices. (It's still technically possible that user input comes in before we initialize the tty, but I think it will probably never happen in practice)

Would you mind giving that a try @neuschaefer ?
