### ISSUE TITLE
Feature request: allow specifying the initial search string

### ISSUE THREAD

**Issue by miikka** [jhawthorn/fzy#9]
Selecta has `-s` and fzf has `-q` for giving the initial query via the command-line. I use it with fzf and it would be great to have it in fzy as well.

**Comment by jhawthorn** [comment]
I would like to implement this. Thank you for the suggestion

**Comment by jhawthorn** [comment]
@miikka This is now in master 6081e91c502c762867bfd9076e7541bd73fb9499

I used `-q` as I'm already using `-s` as an alias for `--show-scores`
