### ISSUE TITLE
fzy -s does not take length of score into account when drawing the screen

### ISSUE THREAD

**Issue by marius** [jhawthorn/fzy#91]
When you have long lines in your zsh history and you run
history 0 | fzy -s
search for some long lines and scroll up and down it garbles the screen.

**Comment by neuschaefer** [comment]
Which version (commit) of fzy are you using?
I remember fixing a very similar bug in commit 887bacc8ae374bdfc528e357d42ec329fccd5981, which was merged after release 0.9.

**Comment by casr** [comment]
`history 0` delimits the history number and the command with a tab. `fzy` counts a tab as one character but displays it as the equivalent of 8 spaces on screen.

```history 0 | tr '[tab character]' ' ' | fzy -s```

might fix this for you. You can type a tab character on the prompt with C-v [tab] (sorry I can't get this comment to display a tab character properly).

Also, #55

**Comment by marius** [comment]
neuschaefer@: Thanks, I think you fix works, verified by building from head.

casr@: Interesting, thanks.
