### ISSUE TITLE
fzy draws multiple result screens

### ISSUE THREAD

**Issue by linhvng** [jhawthorn/fzy#92]
Hello,

Thank you for a great tool! I am currently using `OpenBSD 6.3-stable` with `fzy 0.9 (c) 2014 John Hawthorn`. I have a file which is a result of `find` and `grep`. Here is the file 
[test.txt](https://github.com/jhawthorn/fzy/files/2359292/test.txt). When I do `cat test.txt | fzy`, then start typing more (i.e. 110), this behavior in the screenshot is what I get:

![fzybug](https://user-images.githubusercontent.com/8838571/45195547-30add480-b226-11e8-9460-8bca890f71b2.png)

Testing with `fzf`, this is what I get:

![fzf](https://user-images.githubusercontent.com/8838571/45195572-48855880-b226-11e8-9d94-b06bdfb007a3.png)

I saw other issues regarding `-s` option. I did not use `-s` so I think this is not the same? My apologize if it is... 

Cheers

**Comment by casr** [comment]
Perhaps it is something to do with tabs? Try piping it through this style pipeline:
```
find ... | tr '	' '        ' | fzy
```

where the first argument to `tr` is a tab character. You can type it with C-v [tab].

**Comment by linhvng** [comment]
You are correct! Using the same test.txt, pipe `tr` to trim the `tab` char to `space` does the trick:

`cat test.txt | tr '<ctrl-v + tab>' '<space>' | fzy`

Thank you very much!
