### ISSUE TITLE
Default num_lines limit of 10

### ISSUE THREAD

**Issue by aldanor** [jhawthorn/fzy#97]
fzy is different from most other tools like grep and fzf in that it artificially limits number of lines shown (to 10 lines) which is quite sad if you typical terminal window height is much higher. E.g., just checked the number of rows in my terminal, it's 140, so 10 lines is the 7% tiny bit at the very bottom. Having to type `-l70` every time is a bit bothersome.

I have a few quality-of-life suggestions here:

- Allow for 'unlimited` mode which uses all rows in the terminal (kind of like what fzf does). This could be enabled e.g. via `-l 0`.
- Allow setting the default number of lines when building fzy. E.g., by setting `-DFZY_NUM_LINES=10` (current behaviour), or `-DFZY_NUM_LINES=0` (set unlimited mode as default). This way, the current behaviour could be kept as default (if desired), but the users who'd like it to behave differently could have that as well, without having to pass in command line flags.
- (Optional) Limit num_lines to the current terminal height (e.g. if your terminal is 20 rows high, num_lines=40 makes little sense and is not very ergonomic).

// Thanks for great software :)

**Comment by neuschaefer** [comment]
As a bit of a side note, the last point is somewhat moot, because fzy already doesn't use more lines than the terminal currently has. For example, in my Vim configuration, I always pass `-l 256`, which effectively means "the whole screen".

**Comment by maximbaz** [comment]
You can also consider just adding `alias fzy=fzy -l999` to your `.bashrc`

**Comment by aldanor** [comment]
> You can also consider just adding alias fzy='fzy -l999' to your .bashrc

Of course. But you can't do it, for example, if the bashrc is not yours but the end user's.

> For example, in my Vim configuration, I always pass -l 256

... which kind of confirms my initial point? The num_lines=10 default is a very strange one, so most users would probably override it like you do.

The simplest change, I guess, is just fixing this:

https://github.com/jhawthorn/fzy/blob/f5d41e726cd997ba038815e218c48017228a8f0e/src/options.c#L45

to:

```c
#ifndef FZY_NUM_LINES
#define FZY_NUM_LINES 10
#endif
...
options->num_lines = FZY_NUM_LINES;
```

**Comment by neuschaefer** [comment]
> >   For example, in my Vim configuration, I always pass -l 256
>
> ... which kind of confirms my initial point? The num_lines=10 default is a very strange one, so most users would probably override it like you do.

Sorry, I didn't mean to argue against any of your points, other than the last one ("Limit num_lines to the current terminal height[...]").

**Comment by jhawthorn** [comment]
As others have suggested you can use `-l 999` or even `-l max`.

I really like fzy taking only 10 lines. This was done very intentionally so that it plays nicely when used in a command line. If you never use fzy in this way, I've just pushed up a commit 36cd434ad16bf6b6c62ae82853c91355114602cd which makes it easy to compile fzy with alternate defaults (although an alias is so much easier).
