### ISSUE TITLE
Support `C-g` to exit besides `Esc`

### ISSUE THREAD

**Issue by terlar** [jhawthorn/fzy#99]
As an Emacs-user it would be nice if fzy supported `C-g` to exit besides `Esc` which is a bit harder to reach IMO.

**Comment by casr** [comment]
Most CLI's I have used have `C-d` but I haven't seen `C-g` before. `C-d` is supported already if that suits you?

**Comment by maximbaz** [comment]
`C-c` also works in addition to `C-d`.

**Comment by terlar** [comment]
I guess that could be fine, I realized this after I started looking into how it was implemented. In my mind C-c needs to be supported as that is usually a hard kill. Those two would suit me if you think adding yet another key is too much. Just have to work on my muscle memory. Thanks

**Comment by NightMachinary** [comment]
C-g is used in a lot of emacs packages, adding it doesn't hurt.

**Comment by gpanders** [comment]
Implemented in #125
